### ISSUE TITLE
public release for GitHub Actions

### ISSUE THREAD

**Issue by ctaggart** [AArnott/Nerdbank.GitVersioning#375]
I just merged GitHub Actions build support to `master` and I was hoping for a public release version, but no such luck. I'm sure there is a good solution to check the branch and set the `PublicRelease` environment variable. Just thought I'd bring it up here.

https://github.com/ctaggart/froto/runs/195699232

Another option may be to configure the checkout differently. I'm not sure yet.

**Comment by AArnott** [comment]
Interesting. I guess we need to add GitHub Actions support to [our provider list](https://github.com/AArnott/Nerdbank.GitVersioning/tree/master/src/NerdBank.GitVersioning/CloudBuildServices).

**Comment by AArnott** [comment]
Adding the code to support it is easy. But I don't have GitHub Actions v2 support on my account yet, nor do I know where the docs are for what env vars are set so that we can detect the branch that was (logically) checked out. So I'd love to review a PR if you can send it. Short of that, a link to the docs with the answers would be great.

**Comment by ctaggart** [comment]
You can create a pull request at my froto project to try it out. It is pretty well documented here:
https://github.com/features/actions
https://help.github.com/en/categories/automating-your-workflow-with-github-actions

The current build workflow is here: https://github.com/ctaggart/froto/blob/master/.github/workflows/build.yml

``` yaml
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
    - name: build, test, pack
      run: ./build.sh
    - name: push
      run: |
        source=https://www.myget.org/F/froto/api/v2/package
        key=${{secrets.myget_froto_api_key}} 
        dotnet nuget push -s $source -k $key bin/Froto.Parser.*.nupkg
        dotnet nuget push -s $source -k $key bin/Froto.Serialization.*.nupkg
        dotnet nuget push -s $source -k $key bin/Froto.TypeProvider.DesignTime.*.nupkg
        dotnet nuget push -s $source -k $key bin/Froto.TypeProvider.*.nupkg
```

I learned about them yesterday with this pull request: https://github.com/ctaggart/froto/pull/108

I'm still learning about them. The above workflow is not perfect. `actions/checkout@v1` ends up running this: https://github.com/actions/checkout/blob/master/action.yml . May be I just need to adjust `ref` param.

The setup-dotnet is here: https://github.com/actions/setup-dotnet . I think a `AArnott/Nerdbank.GitVersioning@master` is possible. May be it would do this:
```
    - run: |
      dotnet tool install -g nbgv
      nbgv get-version -f json > nbgv.json
```

I didn't see a good way to pass variables around. The filesystem via files or a `.env` file are probably good options. `jq` could be used by other shell commands. 
```
semver=`jq .SemVer2 nbgv.json -r`
```
