### ISSUE TITLE
Define a GitHub Actions v2 step

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.GitVersioning#377]
The setup-dotnet is here: https://github.com/actions/setup-dotnet . I think a `AArnott/Nerdbank.GitVersioning@master` is possible. May be it would do this:
```
    - run: |
      dotnet tool install -g nbgv
      nbgv get-version -f json > nbgv.json
```

I didn't see a good way to pass variables around. The filesystem via files or a `.env` file are probably good options. `jq` could be used by other shell commands. 
```
semver=`jq .SemVer2 nbgv.json -r`
```

_Originally posted by @ctaggart in https://github.com/AArnott/Nerdbank.GitVersioning/issues/375#issuecomment-522210673_

**Comment by ctaggart** [comment]
I got it working here: https://github.com/ctaggart/nbgv

This works:
```
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ctaggart/nbgv@master
    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
```

I would like to transfer the repo over to you. A GitHub action turns out to just be a Node.js 12 app with this provided API:

https://github.com/actions/toolkit

You end up committing all the production dependencies into git. For local dev, I do:
```
npm install
npm run build
```

Then before pushing it:
```
rm -rf node_modules
npm install --production
```

It turns out that exporting a variable to create an environment variable:
https://github.com/ctaggart/nbgv/blob/master/src/main.ts#L108
```
core.exportVariable('NBGV_CloudBuildNumber', json.CloudBuildAllVars.NBGV_CloudBuildNumber);
```

Is just logging this I think:
```
##[set-env name=NBGV_CloudBuildNumber;]0.7.14+e001f9c
```

🎁
